name: Validate JSON

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: apt install -y jq

      - name: Validate json
        run: jq . data.json
